  {
    name: "",
    name_full: "",
    slug: "",
    age: "",
    job: "",
    location: "",
    origin: "",
    tags:[""],
    player_status: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "",
      instagram_handle: "",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "",
      linkedin_url: "",
      linkedin_job: "",
    },
  },