export const playerData = [
  {
    name: "Aaron",
    name_full: "Aaron Clancy",
    slug: "aaron",
    age: "26",
    job: "Insurance Agent",
    job_full: "Account Executive at Health IQ",
    location: "San Diego, CA",
    origin: "Walnut, California",
    instagram: "https://www.instagram.com/aaronrclancy/",
    instagram_handle: "aaronrclancy",
    tiktok: "",
    instagram_scrubbed: false,
    abc_profile: "https://abc.com/shows/the-bachelorette/cast/aaron-summer-2021",
    gor_assessment_epi: "The Men of Season 17 Volume 1",
    gor_assessment_timestamp: "5:49",
    linkedin: "https://www.linkedin.com/in/aaron-clancy-217bb111a/",
    gor_social_assessment: "weak",
    predictions: {
      limo_exit: "shirtless",
      gameplay: "will take shirt off",
      game_length: "mid-season floater",
    },
    "tags":["ripped"]
  },
  {
    name: "Andrew M",
    name_full: "Andrew Milkovich",
    slug: "andrewm",
    age: "31",
    job: "Deputy District Attorney",
    job_full: "Deputy District Attorney at Orange County District Attorney’s Office",
    location: "Newport Beach, CA",
    origin: "Walnut Creek, California",
    instagram: "https://www.instagram.com/soymilc/",
    instagram_handle: "soymilc",
    instagram_scrubbed: false,
    tiktok: "",
    abc_profile: "https://abc.com/shows/the-bachelorette/cast/andrew-m-summer-2021",
    gor_assessment_epi: "The Men of Season 17 Volume 1",
    gor_assessment_timestamp: "10:22",
    linkedin: "https://www.linkedin.com/in/andrew-milcovich-531916a0/",
    gor_social_assessment: "regular",
    predictions: {
      limo_exit: "",
      gameplay: "",
      game_length: "Pacecase: I think he can do very well",
    },
    "tags":["military", "partier", "lawyer"]
  },
];