export const playerData = [
  {
    name: "Aaron",
    name_full: "Aaron Clancy",
    slug: "aaron",
    age: "26",
    job: "Insurance Agent",
    location: "San Diego, CA",
    origin: "Walnut, California",
    tags:["jacked", "swimmer"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "5:49",
      gor_assessment_timestamp_remaining: "1:25:23",
      predictions: {
        limo_exit: "Shirtless",
        gameplay: "Will take shirt off",
        game_length: "Mid-season floater",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/aaronrclancy/",
      instagram_handle: "aaronrclancy",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/aaron-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/aaron-clancy-217bb111a/",
      linkedin_job: "Account Executive at Health IQ",
    },
  },
  {
    name: "Andrew M",
    name_full: "Andrew Milkovich",
    slug: "andrewm",
    age: "31",
    job: "Deputy District Attorney",
    location: "Newport Beach, CA",
    origin: "Walnut Creek, California",
    tags:["military", "potential partier", "lawyer", "water polo", "California-type"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "10:20",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "PaseCase's Top 4",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/soymilc/",
      instagram_handle: "soymilc",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/andrew-m-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/andrew-milcovich-531916a0/",
      linkedin_job: "Deputy District Attorney at Orange County District Attorney’s Office",
    },
  },
  {
    name: "Andrew S",
    name_full: "Andrew Spencer",
    slug: "andrews",
    age: "26",
    job: "Pro Football Player",
    location: "Vienna, Austria",
    origin: "Waukegan, Illinois",
    tags:["Clay's cousin", "worldly", "football", "beach parties","athlete"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "13:42",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Likely trained by previous players",
        game_length: "Mid to late-season floater; Don't see playoffs but Top 10",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 2,
      hujus: 0,
      ptcs: 1,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/andrewzspencer/?hl=en",
      instagram_handle: "andrewzspencer",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/andrew-s-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Austin",
    name_full: "Austin Tinsley",
    slug: "austin",
    age: "25",
    job: "Real Estate Investor",
    location: "Mission Viejo, CA",
    origin: "Mission Viejo, CA",
    tags:["athlete","track star", "jacked", "family", "gym"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "17:38",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Bad first audience game",
        game_length: "Maybe deep run based on Instagram scrub and/or prepping for influencer",
        notes: "May workout at nude gyms; full assessment of all 9 instagrams",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/austinsley/",
      instagram_handle: "austinsley",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/austin-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Bao",
    name_full: "Bao Wu",
    slug: "bao",
    age: "36",
    job: "Real Estate & Stocks",
    location: "San Diego, CA",
    origin: "",
    tags:["jacked", "cat", "frat energy", "travel"],
    player_status: "sidelined",
    player_status_last_update: "pre-season",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "30:26",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Professional player; strong parasocial gaze",
        game_length: "Playoff-bound",
        notes: "Has some instagram animals; Instagram flirting with peripheral Bachelor universe",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/baochowski/",
      instagram_handle: "baochowski",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Blake",
    name_full: "Blake Moynes",
    slug: "blake",
    age: "30",
    job: "Wildlife Manager",
    location: "Burlington, Ontario, Canada",
    origin: "Burlington, Ontario, Canada",
    tags:["pets", "wildlife", "sex positivity"],
    player_status: "unannounced",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "36:10",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "26th Bachelor; \"Bachelor vibes\"; Does his homework",
        game_length: "Top 6, BachelorClues #5 pick",
        notes: "8th place on Season 16; Would have expected a better Instagram"
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/blakemoynes/",
      instagram_handle: "blakemoynes",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "",
      linkedin_url: "https://www.linkedin.com/in/blake-moynes-1975b41b5/?originalSubdomain=ca",
      linkedin_job: "--",
    },
  },
  {
    name: "Brandon",
    name_full: "Brandon Torres",
    slug: "brandon",
    age: "26",
    job: "Auto Parts Manager",
    location: "Queens, NY",
    origin: "Mokena, IL",
    tags:["motorcycles", "speaks Japanese", "Tokyo"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "41:34",
      gor_assessment_timestamp_remaining: "",
      gor_social_assessment: "",
      predictions: {
        limo_exit: "Aloha (Japanese); Motorcycle grandy",
        gameplay: "",
        game_length: "Night one",
        notes: "Parasocial gaze is not great but he's trying on Instagram",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/amadoseba/",
      instagram_handle: "amadoseba",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/brandon-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/brandon-torres-69298582/",
      linkedin_job: "District Service and Parts Manager at Toyota North America",
    },
  },
  {
    name: "Brendan",
    name_full: "Brendan Scanzano",
    slug: "brendan",
    age: "26",
    job: "Firefighter Trainee",
    location: "Toronto, Ontario, Canada",
    origin: "Toronto, Ontario, Canada",
    tags:["Blake's friend","dog", "travel", "tattoos", "Canadian"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "45:54",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Villain vibes; Rivalry",
        game_length: "",
        notes: "Friends with Blake Moynes; Sunglasses prevent parasocial gaze",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/thebrendanquinn/",
      instagram_handle: "thebrendanquinn",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/brendan-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Christian",
    name_full: "",
    slug: "christian",
    age: "26",
    job: "Real Estate Agent",
    location: "Boston, MA",
    origin: "Newburyport, MA",
    tags:["athletic","MMA fighter", "obstacle experience", "salesman"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "49:27",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Good salesman = good game skills",
        game_length: "Optimistic outlook; one to watch",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/christian.smith17/",
      instagram_handle: "christian.smith17",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/christian-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Cody",
    name_full: "Cody Menk",
    slug: "cody",
    age: "27",
    job: "Zipper Sales Manager",
    location: "San Diego, CA",
    origin: "San Diego, CA",
    tags:["EDM", "tattoos", "music festivals", "weights"],
    player_status: "eliminated",
    player_status_last_update: "2",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "52:37",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Brings a blowup doll (known)",
        gameplay: "Could be 4TWR - promoting business",
        game_length: "Night one guy",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/menkster_/",
      instagram_handle: "menkster_",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "",
      linkedin_url: "https://www.linkedin.com/in/cody-menk-99167487/",
      linkedin_job: "West Coast Regional Account Manager at ZIP-PAK",
    },
  },
  {
    name: "Connor B",
    name_full: "Connor Brennan",
    slug: "connorb",
    age: "29",
    job: "Math Teacher",
    location: "Nashville, TN",
    origin: "Columbia, IL",
    tags:["musician","piano","songwriter", "progressive"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "54:55",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Might be cat TOT limo exit",
        gameplay: "Spritely vibe; class clown",
        game_length: "Bachelor Clue's Top 4",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/connorfalcon/",
      instagram_handle: "connorfalcon",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/connor-b-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Conor C",
    name_full: "Conor Costello",
    slug: "conorc",
    age: "28",
    job: "Former Baseball Player",
    location: "Costa Mesa, CA",
    origin: "Edmond, OK",
    tags:["athlete","baseball","religious", "hunting"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "1:04:36",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Katie Thurston probably doesn't like hunting; Good 2nd audience",
        game_length: "",
        notes: "Mostly with groups and baseball",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/conorcostello4/",
      instagram_handle: "conorcostello4",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/conor-c-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/conor-costello-87657a150/",
      linkedin_job: "Account Manager at Apex Systems",
    },
  },
  {
    name: "David",
    name_full: "David Scott",
    slug: "david",
    age: "27",
    job: "Technical Product Specialist",
    location: "Nashville, TN",
    origin: "New York, NY",
    tags:["basketball","tech"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "1;08:48",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Kind look; Charming & intimiate; Kind & gentle; 4TRR",
        game_length: "Going to crush the game; PaseCase's Top 4",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/dscott530/",
      instagram_handle: "dscott530",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/david-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/david-scott-ba8336ba/",
      linkedin_job: "Technical Product Specialist at Dell EMC",
    },
  },
  {
    name: "Dennis",
    name_full: "Dennis Walega",
    slug: "dennis",
    age: "26",
    job: "Police Officer",
    location: "",
    origin: "Chicago, IL",
    tags:["cop", "religious"],
    player_status: "sidelined",
    player_status_last_update: "pre-season",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "1:12:40",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/denniscwalega",
      instagram_handle: "denniscwalega",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "",
      linkedin_url: "https://www.linkedin.com/in/denniscwalega/",
      linkedin_job: "Police Officer at Village of Barrington Hills",
    },
  },
  {
    name: "Gabriel",
    name_full: "Gabriel Everett",
    slug: "gabriel",
    age: "35",
    job: "Entrepreneur",
    location: "Charlotte, NC",
    origin: "Charlotte, NC",
    tags:["artist","reading","tennis","photography"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "1:18:09",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Camera, picture;",
        gameplay: "Good Instagram; Unattainable vibes",
        game_length: "Could be night one to winner; No clue but could go all the way",
        notes: "Knows Anneliese Puccini",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/gabrielzeverett/",
      instagram_handle: "gabrielzeverett",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/gabriel-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Garrett",
    name_full: "Garrett Schwartz",
    slug: "garrett",
    age: "29",
    job: "Software Marketing Manager",
    location: "Salinas, CA",
    origin: "Salinas, CA",
    tags:["red hair", "dog", "golf", "jacked"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "1:23:00",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "Could go furthest of any red haired person",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "",
      instagram_handle: "garrettschwartz_7",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/garrett-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/garrettschwartz/",
      linkedin_job: "Product Marketing Manager at Adobe",
    },
  },
  {
    name: "Greg",
    name_full: "Greg Grippo",
    slug: "greg",
    age: "27",
    job: "Marketing Sales Representative",
    location: "Edison, NJ",
    origin: "Edison, NJ",
    tags:["dog","bro","family","basketball"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 1",
      gor_assessment_timestamp: "1:25:00",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Strong 3rd audience game",
        game_length: "Front-runner; Hometowns; PaseCase and Bachelor Clue's Top 4",
        notes: "Strong parasocial gaze",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 2,
      hujus: 0,
      ptcs: 1,
      love_level: "LL1",
    },
    social_media: {
      instagram_url: "https://www.instagram.com/greggrippo/",
      instagram_handle: "greggrippo",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/greg-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/greg-grippo-008372135/",
      linkedin_job: "Account Manager at Mondo",
    },
  },
  {
    name: "Hunter",
    name_full: "Hunter Montgomery",
    slug: "hunter",
    age: "34",
    job: "Software Strategist",
    location: "Houston, TX",
    origin: "San Angelo, TX",
    tags:["single dad","former addict","tiktoker", "tattoos", "hunter"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "3:36",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Hero player",
        game_length: "One-on-one but no playoffs; PTC and done; Sand-bound",
        notes: "Instagram is a little blah with no kids",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/hmontgomery/",
      instagram_handle: "hmontgomery",
      tiktok_url: "https://www.tiktok.com/@hmontgomery86",
      tiktok_handle: "hmontgomery86",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/hunter-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "James",
    name_full: "James Bonsall",
    slug: "james",
    age: "30",
    job: "Software Salesman",
    location: "La Jolla, CA",
    origin: "",
    tags:["in a box", "Box Man"],
    player_status: "active",
    player_status_last_update: "",
    gor: {},
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/jamesbonsall_/",
      instagram_handle: "jamesbonsall_",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/james-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/james-bonsall-04489477/",
      linkedin_job: "Human Capital Management",
    },
  },
  {
    name: "Jeff",
    name_full: "Jeff Caravello",
    slug: "jeff",
    age: "31",
    job: "Surgical Skin Salesman",
    location: "Jersey City, NJ",
    origin: "Cranford, NJ",
    tags:["vampire","jacked","lots of TOTs", "surfer", "bro"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "9:56",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Definitely seeing a TOT",
        gameplay: "Businessman-y; Might fit into a fool edit",
        game_length: "Week 3 or 4",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/captainvolcano/?hl=en",
      instagram_handle: "captainvolcano",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/jeff-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/jeffrey-caravello-a5214836/",
      linkedin_job: "Sales Specialist, Orthopedics & Tissue Technologies at Integra LifeSciences",
    },
  },
  {
    name: "John",
    name_full: "John Hersey",
    slug: "john",
    age: "27",
    job: "Bartender",
    location: "Pacific Beach, CA",
    origin: "Santa Cruz, CA",
    tags:["vegetarian","EDM","pilot","surfer","dog","travel"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "14:44",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Reminiscent of Deanie Babies",
        game_length: "Looks too nice to last; Night one; Maybe handsome enough to last longer",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "",
      instagram_handle: "johnalexhersey",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/john-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/johnalexhersey/",
      linkedin_job: "Bartender at Dukes, La Jolla",
    },
  },
  {
    name: "Josh",
    name_full: "Joshua Tylerbest",
    slug: "josh",
    age: "25",
    job: "IT Consultant",
    location: "Miami, FL",
    origin: "Pembroke Pines, FL",
    tags:["cheer squad","NFL",""],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "18:45",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Standy with a cheer performance",
        gameplay: "",
        game_length: "Mid-season floater",
        notes: "Knows Ed Waisbrot",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 1,
      love_level: 0,
    },
    social_media: {
      instagram_url: "",
      instagram_handle: "joshtylerbest",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/josh-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/joshua-tylerbest-a61841bb/",
      linkedin_job: "Workday Sales Solutioning Senior Consultant at Invisors",
    },
  },
  {
    name: "Justin",
    name_full: "Justin Glaze",
    slug: "justin",
    age: "26",
    job: "Investment Sales Consultant",
    location: "Baltimore, MD",
    origin: "Ellicott City, MD",
    tags:["artist","painter"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "22:01",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Kringle that's a painting",
        gameplay: "",
        game_length: "",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/justinglaze/",
      instagram_handle: "justinglaze",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/justin-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/justin-glaze-3a533785/",
      linkedin_job: "DCIO Intermediary Sales Consultant at T. Rowe Price",
    },
  },
  {
    name: "Karl",
    name_full: "Karl Smith",
    slug: "karl",
    age: "34",
    job: "Motivational Speaker",
    location: "Miami, FL",
    origin: "Miami, FL",
    tags:["speaker"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "25:02",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Aloha (French)",
        gameplay: "Manipulation and neuro-linguistic programming; 2nd audience manipulation; 4TWR accusations",
        game_length: "Originally cast for Clare; Clues is excited for his play",
        notes: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/ksmithinspires/",
      instagram_handle: "ksmithinspires",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/karl-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/karl-smith-5bb64399/",
      linkedin_job: "Speaker/ Success Coach",
    },
  },
  {
    name: "Kyle",
    name_full: "Kyle Howard",
    slug: "kyle",
    age: "26",
    job: "Technical Recruiter",
    location: "Fort Lauderdale, FL",
    origin: "Sarasota, FL",
    tags:["travel","bro","sports"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "33:00",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "A contender; Top 4; BachelorClues Top 4 and PaseCase's #5",
        notes: "Josh Murray + Wells Adams",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/kyle_howard1/",
      instagram_handle: "kyle_howard1",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/kyle-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/kyle-howard1/",
      linkedin_job: "Technical Recruiter at Matlen Silver",
    },
  },
  {
    name: "Landon",
    name_full: "Landon Goesling",
    slug: "landon",
    age: "25",
    job: "Basketball Coach",
    location: "Dallas, TX",
    origin: "Bakersfield, CA",
    tags:["basketball","Sunshine","partier","sunglasses"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "36:10",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Has personality; Flame out in rivalry; Accusations of 4TWR",
        game_length: "Not top 4;",
        notes: "Pictured with Drake",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/landongoesling/",
      instagram_handle: "landongoesling",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/landon-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/landon-goesling-37b885154/",
      linkedin_job: "Graduate Assistant Coach at The University of Houston",
    },
  },
  {
    name: "Marcus",
    name_full: "Marcus Lathan",
    slug: "marcus",
    age: "30",
    job: "Real Estate Agent",
    location: "Portland, OR",
    origin: "Vancouver, WA",
    tags:["DJ","neat freak","model"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "39:28",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "Maybe not top 4 but will get a group date rose or two",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/marcus_lathan/",
      instagram_handle: "marcus_lathan",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/marcus-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/marcus-lathan-86034049/",
      linkedin_job: "Operations Manager at Affinity Property Management",
    },
  },
  {
    name: "Marty",
    name_full: "Marty Hargrove",
    slug: "marty",
    age: "25",
    job: "Dancer",
    location: "Reno, NV",
    origin: "",
    tags:["numerology","jacked","partier"],
    player_status: "eliminated",
    player_status_last_update: "1",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "43:44",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "",
        game_length: "",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/marty__mar/",
      instagram_handle: "marty__mar",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/marty-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Michael",
    name_full: "Michael Allio",
    slug: "michael",
    age: "36",
    job: "Business Owner",
    location: "Akron, OH",
    origin: "Akron, OH",
    tags:["single dad","widower"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "47:12",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "PTC: Widower",
        game_length: "Night one guy except has a PTC",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: "LL1",
    },
    social_media: {
      instagram_url: "https://www.instagram.com/michael_alliol4/",
      instagram_handle: "michael_alliol4",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/michael-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/michael-allio-9a31a08/",
      linkedin_job: "Founder, Aspiring Do-Gooder at The L4 Project",
    },
  },
  {
    name: "Mike",
    name_full: "Mike Planeta",
    slug: "mike",
    age: "31",
    job: "Gym Owner",
    location: "San Diego, CA",
    origin: "Surprise, AZ",
    tags:["baseball","athletic","religious","travel"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "51:28",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Religious TOT",
        gameplay: "",
        game_length: "Night one guy -- too religious too fast",
        notes: "Has a highlight for Jesus on Instagram",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 0,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/mikeyplaneta/",
      instagram_handle: "mikeyplaneta",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/mike-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/mike-planeta-113522126/",
      linkedin_job: "Student at Point Loma Nazarene University",
    },
  },
  {
    name: "Quartney",
    name_full: "Quartney Mixon",
    slug: "quartney",
    age: "26",
    job: "Nutrition Entrepreneur",
    location: "Dallas, TX",
    origin: "Arlington, TX",
    tags:["gym","fitness","religious","family"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "56:00",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "PTC of mother passing away; Romantic gestures",
        game_length: "Contender; Strong Instagram; PaseCase and Bachelor Clue's Top 4",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/quartneymixon/",
      instagram_handle: "quartneymixon",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: false,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/quartney-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/qmixon/",
      linkedin_job: "Medical Sales Representative at CPM Medical",
    },
  },
  {
    name: "Thomas",
    name_full: "Thomas Jacobs",
    slug: "thomas",
    age: "28",
    job: "Real Estate Broker",
    location: "Poway, CA",
    origin: "San Diego, CA",
    tags:["dogs","family"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "1:02:20",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "Pizza Kringle because he likes food",
        gameplay: "",
        game_length: "Night one because there's nothing to go off of",
        notes: "4 Instagram posts",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 2,
      hujus: 1,
      ptcs: 0,
      love_level: "LL1",
    },
    social_media: {
      instagram_url: "https://www.instagram.com/thomasajacobs/",
      instagram_handle: "thomasajacobs",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/thomas-summer-2021",
      linkedin_url: "",
      linkedin_job: "",
    },
  },
  {
    name: "Tre",
    name_full: "Tré Cooper",
    slug: "tre",
    age: "26",
    job: "Software Engineer",
    location: "Covington, GA",
    origin: "Covington, GA",
    tags:["family"],
    player_status: "active",
    player_status_last_update: "",
    gor: {
      gor_assessment_epi: "The Men of Season 17 Volume 2",
      gor_assessment_timestamp: "1:07:38",
      gor_assessment_timestamp_remaining: "",
      predictions: {
        limo_exit: "",
        gameplay: "Nothing to go off of",
        game_length: "",
        notes: "4 post Instagram",
      },
    },
    season_stats: {
      season: "The Bachelorette Season 17",
      roses: 1,
      hujus: 0,
      ptcs: 0,
      love_level: 0,
    },
    social_media: {
      instagram_url: "https://www.instagram.com/_trecooper/",
      instagram_handle: "_trecooper",
      tiktok_url: "",
      tiktok_handle: "",
      instagram_scrubbed: true,
      abc_profile: "https://abc.com/shows/the-bachelorette/cast/tre-summer-2021",
      linkedin_url: "https://www.linkedin.com/in/tre-vaughn-cooper-a6aa53144/",
      linkedin_job: "--",
    },
  },
];